export * from "./AdminStatsCardsSkeleton";
export * from "./AdminTableSectionSkeleton";
export * from "./AdminModuleListSkeleton";
export * from "./AdminCourseDetailSkeleton";
export * from "./AdminCoursesPageSkeleton";
export * from "./AdminActivityFormSkeleton";
export * from "./AdminStudentDetailSkeleton";
export * from "./AdminTransactionsSkeleton";
export * from "./AdminInstructorListSkeleton";
